spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudemo
    username: root
    password: Malware99
  jpa:
    datasource-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    general-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8082
